version: '3.6'

services:
  diaspora:
    image: koehn/diaspora:latest 
    links:
      - postgres
      - redis
    volumes:
      - diaspora-images:/home/diaspora/diaspora/public/uploads/images
      - ./diaspora.yml:/home/diaspora/diaspora/config/diaspora.yml:ro
      - ./database.yml:/home/diaspora/diaspora/config/database.yml:ro
#    ports:
#      - '3000:3000'
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST='diaspora.davidmaxson.name'
      - VIRTUAL_PORT=3000
    restart: always
    networks:
      - default
#      - webnet
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        window: 5s

  postgres:
    read_only: true
    image: postgres:alpine
    tmpfs:
    - /tmp
    environment:
      - POSTGRES_USER=diaspora
      - POSTGRES_PASSWORD=somepassword
      - POSTGRES_DB=diaspora_production
    volumes:
      - postgres:/var/lib/postgresql/data
      - postgres-run:/var/run/postgresql
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        window: 5s

  redis:
    image: redis:alpine
    read_only: true
    command: redis-server --appendonly yes
    volumes:
      - type: volume
        target: /data
        source: redis
      - type: tmpfs
        target: /tmp
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        window: 5s

volumes:
  diaspora-images:
  postgres:
  postgres-run:
  redis:

networks:
  webnet:
    external:
      name: webnet
